Enforce strict settings with 'set' and few changes to make it work

diff --git a/timer b/timer
--- a/timer
+++ b/timer
@@ -4,33 +4,13 @@
 # Forked, made more modern and extended from script written by Timothy Lin.
 # https://github.com/lzh9102/bash-countdown
 
-# TODO:
-
-# - Support more terminals for tab title update.
-# - -d --daemon -optio. ajetaan kokonaan taustalla.
-#     kävis näin: echo 'sleep N; {command}' | at now tai
-#     (sleep N; {command}) &
-  
-# - jos nykyinen ja timeup -aika on samalla vuorokaudella, tulosta vain kellon
-#   aika (date +%T)
-# - timerin ajo taustalle &:lla toimimaan kunnolla.
-# - samoin jos käyttää Ctrl-z, että kursori palautuisi.
-# - optio, jolla figletillä printataan jäljellä oleva aika samassa muodossa,
-#   kuin tabi-tekstissä?
-
-# standard inputista lukeminen
-# https://stackoverflow.com/questions/18761209/how-to-make-a-bash-function-which-can-read-from-standard-input
-
-# set -o errexit   # abort on non-zero exit status
-# set -o nounset   # abort on unbound variable
+set -o errexit   # abort on non-zero exit status
+set -o nounset   # abort on unbound variable
 set -o pipefail  # don't hide errors within pipes
-
-# If settings variables are not defined, use defaults.
-
-# Settings below should be either true or false.
 
 interrupt_message="Countdown stopped by user interrupt."
 
+# Settings below should be either "true" or "false".
 show_progress_bar="false"  # Progress bar visibility.
 update_tab_title="true"    # Print countdown time to tab title.
 CLEAR_SCREEN="false"       # Clear screen at timeup.
@@ -227,7 +207,7 @@ function quit () {
 
     if [[ $CLEAR_SCREEN == true ]]; then
         clear
-    elif [[ -n "$2" ]]; then
+    elif [[ -n "${2:-}" ]]; then
         echo -e "\n$2"
     fi
 
@@ -342,6 +322,8 @@ fi
 check_terminal
 prepare_screen
 
+lines=0
+
 # Countdown
 while [[ $sec_rem -gt 0 ]]; do
     # Calculate remaining seconds
@@ -376,7 +358,7 @@ while [[ $sec_rem -gt 0 ]]; do
     printf "%0.s-" {1..35}; echo
 
     # Check how many lines we need for output once.
-    if [[ -z $lines ]]; then
+    if [[ $lines == 0 ]]; then
         if [ $hours -gt 0 ]; then
             readonly lines=3
         elif [ $minutes -gt 0 ]; then
@@ -399,7 +381,8 @@ while [[ $sec_rem -gt 0 ]]; do
 
     echo "Press [q] to stop counting           "
 
-    read -n 1 -t 1 ch
+    # Wait a second and quit if user press 'q' else continue.
+    read -n 1 -t 1 ch || true
     [[ "$ch" == "q" ]] && quit 1 "$interrupt_message"
 done
 
