refactor: indention to 4 spaces

diff --git a/timer b/timer
--- a/timer
+++ b/timer
@@ -91,102 +91,102 @@ Options:
 # function to get seconds from (hours,minutes,seconds)
 # usage: print_seconds days hours minutes seconds
 function print_seconds () {
-  if [[ $# -ne 4 ]]; then
-    echo "Error: function print_seconds takes 4 parameters" >&2
-    exit 1
-  fi
-  # hours, minutes, seconds
-  result=$(( $2 * 3600 + $3 * 60 + $4 ))
-  echo "$result"
+    if [[ $# -ne 4 ]]; then
+        echo "Error: function print_seconds takes 4 parameters" >&2
+        exit 1
+    fi
+    # hours, minutes, seconds
+    result=$(( $2 * 3600 + $3 * 60 + $4 ))
+    echo "$result"
 }
 
 # Correct date by trying to add some time to it.
 # usage: correct_date_sec seconds
 function correct_date_sec () {
-  final=$1
-  if [[ "$final" -gt 0 ]]; then
-    echo "$final"
-    return
-  fi
-  final=$(( $1 + SEC_PER_DAY ))
-  if [[ "$final" -gt 0 ]]; then
-    echo "$final"
-    return
-  fi
-  echo "0"
+    final=$1
+    if [[ "$final" -gt 0 ]]; then
+        echo "$final"
+        return
+    fi
+    final=$(( $1 + SEC_PER_DAY ))
+    if [[ "$final" -gt 0 ]]; then
+        echo "$final"
+        return
+    fi
+    echo "0"
 }
 
 # If no parameters is given.
 if [[ $# -eq 0 ]]; then
-  show_hint
-  exit 1
+    show_hint
+    exit 1
 fi
 
 # identify the time format and assign number of seconds by print_seconds.
 function assign_time () {
-  # H:M:S
-  if [[ "$parameter" =~ ^([0-9]+):([0-9]+):([0-9]+)$ ]]; then
-    sec_rem=$(print_seconds 0 BASH_REMATCH[1] BASH_REMATCH[2] BASH_REMATCH[3])
-  # M:S
-  elif [[ "$parameter" =~ ^([0-9]+):([0-9]+)$ ]]; then
-    sec_rem=$(print_seconds 0 0 BASH_REMATCH[1] BASH_REMATCH[2])
-  # M. Defaults if number is given without letter.
-  elif [[ "$parameter" =~ ^([0-9]+)$ ]]; then
-    sec_rem=$(print_seconds 0 0 BASH_REMATCH[1] 0)
-  # Verbal formats, seconds (if time unit starts with 's').
-  elif [[ "$parameter" =~ ^([0-9]+)s(.*) ]]; then
-    sec_more=$(print_seconds 0 0 0 BASH_REMATCH[1])
-  # Add to existing time so they can be combined.
-    sec_rem=$(( sec_rem + sec_more))
-  # Minutes
-  elif [[ "$parameter" =~ ^([0-9]+)m(.*) ]]; then
-    sec_more=$(print_seconds 0 0 BASH_REMATCH[1] 0)
-    sec_rem=$(( sec_rem + sec_more))
-  # Hours
-  elif [[ "$parameter" =~ ^([0-9]+)h(.*) ]]; then
-    sec_more=$(print_seconds 0 BASH_REMATCH[1] 0 0)
-    sec_rem=$(( sec_rem + sec_more))
-  else
-    if [[ "${previous_parameter:0:1}" == "-" ]]; then
-      echo "Error: Not a valid option: \"$previous_parameter\". \
-Type $("basename" "$0") -h for help." >&2
-      exit 1
+    # H:M:S
+    if [[ "$parameter" =~ ^([0-9]+):([0-9]+):([0-9]+)$ ]]; then
+        sec_rem=$(print_seconds 0 BASH_REMATCH[1] BASH_REMATCH[2] BASH_REMATCH[3])
+    # M:S
+    elif [[ "$parameter" =~ ^([0-9]+):([0-9]+)$ ]]; then
+        sec_rem=$(print_seconds 0 0 BASH_REMATCH[1] BASH_REMATCH[2])
+    # M. Defaults if number is given without letter.
+    elif [[ "$parameter" =~ ^([0-9]+)$ ]]; then
+        sec_rem=$(print_seconds 0 0 BASH_REMATCH[1] 0)
+    # Verbal formats, seconds (if time unit starts with 's').
+    elif [[ "$parameter" =~ ^([0-9]+)s(.*) ]]; then
+        sec_more=$(print_seconds 0 0 0 BASH_REMATCH[1])
+    # Add to existing time so they can be combined.
+        sec_rem=$(( sec_rem + sec_more))
+    # Minutes
+    elif [[ "$parameter" =~ ^([0-9]+)m(.*) ]]; then
+        sec_more=$(print_seconds 0 0 BASH_REMATCH[1] 0)
+        sec_rem=$(( sec_rem + sec_more))
+    # Hours
+    elif [[ "$parameter" =~ ^([0-9]+)h(.*) ]]; then
+        sec_more=$(print_seconds 0 BASH_REMATCH[1] 0 0)
+        sec_rem=$(( sec_rem + sec_more))
     else
-      true
-      # TODO: Do these need to be added?
-      # echo "Error: Couldn't parse time format for: \"$parameter\".
-      # Type $("basename" "$0") -h for help."
-      # exit 1
+        if [[ "${previous_parameter:0:1}" == "-" ]]; then
+            echo "Error: Not a valid option: \"$previous_parameter\". \
+Type $("basename" "$0") -h for help." >&2
+            exit 1
+        else
+            true
+            # TODO: Do these need to be added?
+            # echo "Error: Couldn't parse time format for: \"$parameter\".
+            # Type $("basename" "$0") -h for help."
+            # exit 1
+        fi
     fi
-  fi
 }
 
 # Set countdown at certain clock time.
 function set_at_time() {
-  UNTIL=$(date -d "$parameter" +%s)
-  if [[ $? -ne 0 ]]; then
-    exit 1
-  fi
-  sec_rem=$(( UNTIL - time_now ))
-  if [[ $sec_rem -lt 1 ]]; then
-    sec_rem=$(correct_date_sec $sec_rem)
-    if [[ "$sec_rem" -lt 1 ]]; then
-      echo "Error: The date $parameter is already history." >&2
-      exit 1
-    fi
-    # there's no "-f" option
-    if [[ -z "$NO_CONFIRM" ]]; then
-      # confirm for the correction
-      echo "Warning: The given date is assumed to be: $(date -d now\ +"$sec_rem"\ sec)"
-      echo "Place an option -f before -d to suppress this warning"
-      read -n 1 -p -r "Still proceed [Y]/n?" ch
-      echo
-      if [[ "$ch" == "n" || "$ch" == "N" ]]; then
+    UNTIL=$(date -d "$parameter" +%s)
+    if [[ $? -ne 0 ]]; then
         exit 1
-      fi
-      ch=""
     fi
-  fi
+    sec_rem=$(( UNTIL - time_now ))
+    if [[ $sec_rem -lt 1 ]]; then
+        sec_rem=$(correct_date_sec $sec_rem)
+        if [[ "$sec_rem" -lt 1 ]]; then
+            echo "Error: The date $parameter is already history." >&2
+            exit 1
+        fi
+        # there's no "-f" option
+        if [[ -z "$NO_CONFIRM" ]]; then
+            # confirm for the correction
+            echo "Warning: The given date is assumed to be: $(date -d now\ +"$sec_rem"\ sec)"
+            echo "Place an option -f before -d to suppress this warning"
+            read -n 1 -p -r "Still proceed [Y]/n?" ch
+            echo
+            if [[ "$ch" == "n" || "$ch" == "N" ]]; then
+                exit 1
+            fi
+            ch=""
+        fi
+    fi
 }
 
 # Parse command line options
@@ -231,16 +231,16 @@ total_time=$(( until_date - $(date +%s) ))
 
 # usage: quit <exit code> [quit message]
 function quit () {
-  # Restore cursor
-  tput cnorm
-  # Restore keyboard echo
-  stty echo
+    # Restore cursor
+    tput cnorm
+    # Restore keyboard echo
+    stty echo
 
-  if [[ $CLEAR_SCREEN == true ]]; then
-    clear
-  fi
+    if [[ $CLEAR_SCREEN == true ]]; then
+        clear
+    fi
 
-  exit "$1"
+    exit "$1"
 }
 # set the quit function to be the Control+C handler
 trap 'quit 1 "$interrupt_message"' INT
@@ -248,112 +248,112 @@ trap 'quit 1 "$interrupt_message"' INT
 # Print terminal tab title
 # Usage: print_title <title>
 function print_title () {
-  # Some terminals accept only different commands.
-  case "$terminal" in
-    yakuake)
-      # Doesn't work if we are root.
-      [[ "$EUID" == 0 ]] && return
-      # Yakuake uses qdbus to set titles.
-      qdbus org.kde.yakuake /yakuake/tabs setTabTitle "$session_id" "$tab_title"
-      ;;
-    terminator)
-      printf '\033]0;%s\a' "$tab_title" ;;
-    *) printf '\e]1;%s\a' "$tab_title"  ;;
-  esac
+    # Some terminals accept only different commands.
+    case "$terminal" in
+        yakuake)
+            # Doesn't work if we are root.
+            [[ "$EUID" == 0 ]] && return
+            # Yakuake uses qdbus to set titles.
+            qdbus org.kde.yakuake /yakuake/tabs setTabTitle "$session_id" "$tab_title"
+            ;;
+        terminator)
+            printf '\033]0;%s\a' "$tab_title" ;;
+        *) printf '\e]1;%s\a' "$tab_title"  ;;
+    esac
 }
 
 # checks if we are running terminal which needs different commands for settings
 # a tab title.ausage: check_terminal
 function check_terminal () {
-  terminal=$(ps -o comm= -p $(ps -o ppid= -p "$PPID"))
-  if [[ $terminal == yakuake ]]; then
-    # .. find find out the right Yakuake session_id if we aren't root.
-    # It's used to send commands to Yakuake like to set tab titles in titles.zsh.
-    if [[ $UID != 0 ]] ; then
-      session_id=$(qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.activeSessionId)
+    terminal=$(ps -o comm= -p $(ps -o ppid= -p "$PPID"))
+    if [[ $terminal == yakuake ]]; then
+        # .. find find out the right Yakuake session_id if we aren't root.
+        # It's used to send commands to Yakuake like to set tab titles in titles.zsh.
+        if [[ $UID != 0 ]]; then
+            session_id=$(qdbus org.kde.yakuake /yakuake/sessions org.kde.yakuake.activeSessionId)
+        fi
     fi
-  fi
 }
 
 # print a progress bar
 # usage: show_progress_bar
 function show_progress_bar () {
-  # Tämän pitäis mennä kuin sekunnit eteenpäin, mutta menee hieman nopeampaa ja
-  # epäsynkkaan.
-  # progress=$[$progress + 1]
-  # progress=$[$total_time - $sec_rem]
-  # Progress bar character length
-  bar_length=$(( col * percent / 100 ))
-  # sec_done=$[$total_time - $sec_rem]
-  printf "["
-  # printf "%*s" $COLUMNS "]"
+    # Tämän pitäis mennä kuin sekunnit eteenpäin, mutta menee hieman nopeampaa ja
+    # epäsynkkaan.
+    # progress=$[$progress + 1]
+    # progress=$[$total_time - $sec_rem]
+    # Progress bar character length
+    bar_length=$(( col * percent / 100 ))
+    # sec_done=$[$total_time - $sec_rem]
+    printf "["
+    # printf "%*s" $COLUMNS "]"
 
-  # Assign output to variable f which is used in next command.
-  printf -v f "%${bar_length}s>"
+    # Assign output to variable f which is used in next command.
+    printf -v f "%${bar_length}s>"
 
-  # printf -v f "%$(echo $bar_length)s>"
-  printf "%s\r" "${f// /=}"
+    # printf -v f "%$(echo $bar_length)s>"
+    printf "%s\r" "${f// /=}"
 
-  # Print the "]" to the end of bar.
-  # TODO: rivi muuttuja row määrittely ei toimi, jos title tai message on yli
-  # rivin mittainen. pitäisi saada silleen, että riviä ei tarvi erikseen
-  # määritellä, vaan tekee samalle riville, mihin edellinen komento.
-  tput cup $row $(( col + 2 ))
+    # Print the "]" to the end of bar.
+    # TODO: rivi muuttuja row määrittely ei toimi, jos title tai message on yli
+    # rivin mittainen. pitäisi saada silleen, että riviä ei tarvi erikseen
+    # määritellä, vaan tekee samalle riville, mihin edellinen komento.
+    tput cup $row $(( col + 2 ))
 
-  printf "]\n\n"
-  if [[ $debug_mode == "true" ]]; then
-    echo "Debug:                       "
-    echo "Total time: " $total_time "  "
-    echo "Remaining:  " $sec_rem "     "
-    echo "Bar length  " $bar_length "  "
-    echo "                             "
-  fi
-  # percent=$[$progress * 100 / $total_time]
+    printf "]\n\n"
+    if [[ $debug_mode == "true" ]]; then
+        echo "Debug:                       "
+        echo "Total time: " $total_time "  "
+        echo "Remaining:  " $sec_rem "     "
+        echo "Bar length  " $bar_length "  "
+        echo "                             "
+    fi
+    # percent=$[$progress * 100 / $total_time]
 }
 
 # If silent attribute is given countdown with no output.
 function silent_countdown() {
-  while [[ $sec_rem -gt 0 ]]; do
-    # calculate remaining seconds
-    sec_rem=$(( until_date - time_now ))
+    while [[ $sec_rem -gt 0 ]]; do
+        # calculate remaining seconds
+        sec_rem=$(( until_date - time_now ))
 
-    # Calculate progress percent.
-    percent=$(( (total_time - sec_rem) * 100 / total_time ))
+        # Calculate progress percent.
+        percent=$(( (total_time - sec_rem) * 100 / total_time ))
 
-    # # Calculate the date of timeout once
-    # if [[ -z "$TIMEOUT_DATE" ]]; then
-    #   TIMEOUT_DATE=$(date -d "now +$sec_rem sec" )
-    # fi
-    # wait for 0.9 second and monitor user input
-    read -r -n 1 -t 1 ch
-    if [[ "$ch" == q ]]; then
-      quit 1 "$interrupt_message"
-    fi
-  done
+        # # Calculate the date of timeout once
+        # if [[ -z "$TIMEOUT_DATE" ]]; then
+        #   TIMEOUT_DATE=$(date -d "now +$sec_rem sec" )
+        # fi
+        # wait for 0.9 second and monitor user input
+        read -r -n 1 -t 1 ch
+        if [[ "$ch" == q ]]; then
+            quit 1 "$interrupt_message"
+        fi
+    done
 
-  quit 0
+    quit 0
 }
 
 # Prepare screen for countdown.
 function prepare_screen() {
-  clear
-  # tput cup 0 0
-  # hide cursor
-  tput civis
-  # disable keyboard echo
-  stty -echo
+    clear
+    # tput cup 0 0
+    # hide cursor
+    tput civis
+    # disable keyboard echo
+    stty -echo
 }
 
 
 function if_running_background() {
-  [[ $(ps -o stat= -p $$) != *+* ]]
+    [[ $(ps -o stat= -p $$) != *+* ]]
 }
 
 # Calculate the date of timeout
 TIMEOUT_DATE=$(date -d "now +$sec_rem sec" )
 
 if [[ $be_silent == true ]] || if_running_background; then
-  silent_countdown
+    silent_countdown
 fi
 
 check_terminal
@@ -396,29 +396,30 @@ while [[ $sec_rem -gt 0 ]]; do
     # Check how many lines we need for output once.
     if [[ -z $lines ]]; then
         if [ $hours -gt 0 ]; then
-          readonly lines=3
+            readonly lines=3
         elif [ $minutes -gt 0 ]; then
-          readonly lines=2
+            readonly lines=2
         else
-          readonly lines=1
+            readonly lines=1
         fi
     fi
 
-     # Print necessary lines based on the original time.
-     [[ $hours -ge 3 ]] && echo "Hours:    $hours                     "
-     [[ $lines -ge 2 ]] && echo "Minutes:  $minutes                   "
-     printf "Seconds:  $seconds"
-     printf "%0.s " {1..33}
-     echo -e "\nProgress: $percent %                 "
-     printf "%0.s " {1..33}
-     echo
+    # Print necessary lines based on the original time.
+    [[ $hours -ge 3 ]] && echo "Hours:    $hours                     "
+    [[ $lines -ge 2 ]] && echo "Minutes:  $minutes                   "
+    printf "Seconds:  $seconds"
+    printf "%0.s " {1..33}
+    echo -e "\nProgress: $percent %                 "
+    printf "%0.s " {1..33}
+    echo
 
-     [[ $show_progress_bar == true ]] && show_progress_bar
+    [[ $show_progress_bar == true ]] && show_progress_bar
 
-     echo "Press [q] to stop counting           "
+    echo "Press [q] to stop counting           "
 
-     read -n 1 -t 1 ch
-     [[ "$ch" == "q" ]] && quit 1 "$interrupt_message"
+    read -n 1 -t 1 ch
+    [[ "$ch" == "q" ]] && quit 1 "$interrupt_message"
 done
 
 quit 0
+# vim: set expandtab shiftwidth=4 softtabstop=4 :
